### ISSUE TITLE
Pauli matrices - formula 3.3 - change in formula

### ISSUE THREAD

**Issue by n0542344** [rrtucci/QC-Paulinesia#1]
Thanks for the awesome QC-Paulinesia-book! That's far from my expertise, but I'm enjoying it very much.

Just a minor thing: I'm currently reading through chapter 3 and found the following part in formula 3.3 (file 'chapters/pauli-mats.tex', line 45ff.) which I didn't understand:

    [...]
    Distinct Pauli matrices anticommute. For example,
    
    \beq
    \sigx\sigx = -\sigy\sigx
    \;.
    \label{eq-sig-anticom}
    \eeq
    [...]

Are you sure that is correct? I would have guessed that you might wanted to write (showing only line 48): 

    [...]
    \sigx\sigy = -sigy\sigx
    [...]

Best wishes, Alex
(life science PhD-student from Vienna, Austria)

**Comment by rrtucci** [comment]
Thank you! I fixed it. I would like to thank people in the README for
pointing out errors. If you send me your name, you will be the first one
listed. Thanks again.
Regards, Bob Tucci
